### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by HonorVanEr** [kyruzic/Raytrace-Model#2]
Some functions are missing, such as  raytrace_3d_sp() and gen_iono_grid_3d(). Can you upload them?

**Comment by kyruzic** [comment]
Those functions are not written by me or available for distribution by myself. So no I cannot upload them. If you let me know more about what you're trying to do with this I can point you towards who would be able to get you them.

**Comment by HonorVanEr** [comment]
I am trying to implement an HF ray tracing program based on my ionospheric model. But I don't have programming experience in this area. These two functions have very important reference significance for me.

**Comment by HonorVanEr** [comment]
> Those functions are not written by me or available for distribution by myself. So no I cannot upload them. If you let me know more about what you're trying to do with this I can point you towards who would be able to get you them.

**Comment by kyruzic** [comment]
I'm going to close this issue. Please contact me directly via email and I'll help you out.
